node {
    stage('Clone Repository'){
        git credentialsId: 'github-cred', url: 'https://github.com/pilutpi/simple-python-pyinstaller-app.git', branch: "master"
    }
    stage('Build') {
        docker.image('python:2-alpine').inside {
            // Compile the Python scripts
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        }
        junit 'test-reports/results.xml'
    }
}
